Repository AWS03-CloudSchool/be_tuktuk, pull requests merged in 2024-01, with the labels that each got.

#4 feat(borrow,gamematch): 풋살장 대여와 경기 매칭을 위한 도메인 설계
  src/main/java/com/example/tuktuk/domain/borrow/Borrow.java
  src/main/java/com/example/tuktuk/domain/borrow/BorrowStatus.java
  src/main/java/com/example/tuktuk/domain/gamematch/Game.java
  src/main/java/com/example/tuktuk/domain/gamematch/GameStatus.java
  src/main/java/com/example/tuktuk/domain/global/DailySchedule.java
  src/main/java/com/example/tuktuk/domain/global/Reservation.java
  src/main/java/com/example/tuktuk/domain/global/SliceTime.java
  src/main/java/com/example/tuktuk/domain/global/SliceTimeStatus.java
  src/main/java/com/example/tuktuk/domain/member/Member.java
  src/main/java/com/example/tuktuk/domain/member/Residence.java
  src/main/java/com/example/tuktuk/domain/stadium/Court.java
  src/main/java/com/example/tuktuk/domain/stadium/CourtType.java
  src/main/java/com/example/tuktuk/domain/stadium/Location.java
  src/main/java/com/example/tuktuk/domain/stadium/Stadium.java
Labels: New Feature

#5 2 domain design
  build.gradle
  src/main/java/com/example/tuktuk/domain/borrow/Borrow.java
  src/main/java/com/example/tuktuk/domain/gamematch/Game.java
  src/main/java/com/example/tuktuk/domain/global/SliceTime.java
  src/main/java/com/example/tuktuk/domain/member/Member.java
  src/main/java/com/example/tuktuk/domain/member/Residence.java
  src/main/java/com/example/tuktuk/domain/stadium/Court.java
  src/main/java/com/example/tuktuk/domain/stadium/Location.java
  src/main/java/com/example/tuktuk/domain/stadium/Stadium.java
Labels: New Feature

#6 refactor(all): value 타입을 사용하여 명확하게 코드 리펙토링
  src/main/java/com/example/tuktuk/domain/court/Court.java
  src/main/java/com/example/tuktuk/domain/court/CourtId.java
  src/main/java/com/example/tuktuk/domain/court/CourtType.java
  src/main/java/com/example/tuktuk/domain/event/DailySchedule.java
  src/main/java/com/example/tuktuk/domain/event/Reservation.java
  src/main/java/com/example/tuktuk/domain/event/SliceTime.java
  src/main/java/com/example/tuktuk/domain/event/SliceTimeStatus.java
  src/main/java/com/example/tuktuk/domain/event/borrow/Borrow.java
  src/main/java/com/example/tuktuk/domain/event/borrow/BorrowStatus.java
  src/main/java/com/example/tuktuk/domain/event/borrow/Borrower.java
  src/main/java/com/example/tuktuk/domain/event/gamematch/Game.java
  src/main/java/com/example/tuktuk/domain/event/gamematch/GameStatus.java
  src/main/java/com/example/tuktuk/domain/event/gamematch/Participant.java
  src/main/java/com/example/tuktuk/domain/global/Money.java
  src/main/java/com/example/tuktuk/domain/member/Member.java
  src/main/java/com/example/tuktuk/domain/member/MemberId.java
  src/main/java/com/example/tuktuk/domain/member/Password.java
  src/main/java/com/example/tuktuk/domain/stadium/Owner.java
  src/main/java/com/example/tuktuk/domain/stadium/Stadium.java
  src/main/java/com/example/tuktuk/domain/stadium/StadiumId.java
Labels: refactor

#7 2 domain design
  src/main/java/com/example/tuktuk/domain/court/Court.java
  src/main/java/com/example/tuktuk/domain/event/DailySchedule.java
  src/main/java/com/example/tuktuk/domain/event/Reservation.java
  src/main/java/com/example/tuktuk/domain/event/Slice.java
  src/main/java/com/example/tuktuk/domain/event/SliceId.java
  src/main/java/com/example/tuktuk/domain/event/SliceStatus.java
  src/main/java/com/example/tuktuk/domain/event/SliceTime.java
  src/main/java/com/example/tuktuk/domain/event/Time.java
  src/main/java/com/example/tuktuk/domain/event/borrow/Borrow.java
  src/main/java/com/example/tuktuk/domain/event/gamematch/Game.java
  src/main/java/com/example/tuktuk/domain/global/Money.java
  src/main/java/com/example/tuktuk/domain/global/Reservation.java
  src/main/java/com/example/tuktuk/domain/global/ReservationId.java
  src/main/java/com/example/tuktuk/domain/stadium/OwnerId.java
  src/main/java/com/example/tuktuk/domain/stadium/Stadium.java
Labels: New Feature

#8 refactor(all): 도메인 확실하게 분류 및 패키지 정리 #2
  src/main/java/com/example/tuktuk/domain/event/DailySchedule.java
  src/main/java/com/example/tuktuk/domain/event/Slice.java
  src/main/java/com/example/tuktuk/domain/member/Member.java
  src/main/java/com/example/tuktuk/domain/reservation/Reservation.java
  src/main/java/com/example/tuktuk/domain/reservation/ReservationId.java
  src/main/java/com/example/tuktuk/domain/slice/Slice.java
  src/main/java/com/example/tuktuk/domain/slice/SliceId.java
  src/main/java/com/example/tuktuk/domain/slice/SliceStatus.java
  src/main/java/com/example/tuktuk/domain/slice/Time.java
  src/main/java/com/example/tuktuk/domain/slice/borrow/Borrow.java
  src/main/java/com/example/tuktuk/domain/slice/borrow/BorrowStatus.java
  src/main/java/com/example/tuktuk/domain/slice/borrow/Borrower.java
  src/main/java/com/example/tuktuk/domain/slice/gamematch/Game.java
  src/main/java/com/example/tuktuk/domain/slice/gamematch/GameStatus.java
  src/main/java/com/example/tuktuk/domain/slice/gamematch/Participant.java
  src/main/java/com/example/tuktuk/domain/stadium/Court.java
  src/main/java/com/example/tuktuk/domain/stadium/CourtId.java
  src/main/java/com/example/tuktuk/domain/stadium/CourtType.java
  src/main/java/com/example/tuktuk/domain/stadium/Owner.java
  src/main/java/com/example/tuktuk/domain/stadium/OwnerId.java
  src/main/java/com/example/tuktuk/domain/stadium/Stadium.java
Labels: refactor

#10 불필요한 주석 제거 및 영문 주석 작성
  build.gradle
  src/main/java/com/example/tuktuk/domain/reservation/Reservation.java
  src/main/java/com/example/tuktuk/domain/slice/Slice.java
  src/main/java/com/example/tuktuk/domain/slice/Time.java
  src/main/java/com/example/tuktuk/domain/slice/gamematch/Game.java
  src/main/java/com/example/tuktuk/domain/stadium/Court.java
  src/main/java/com/example/tuktuk/domain/stadium/Location.java
  src/main/java/com/example/tuktuk/domain/stadium/Stadium.java
  src/main/java/com/example/tuktuk/domain/user/Password.java
  src/main/java/com/example/tuktuk/domain/user/Residence.java
  src/main/java/com/example/tuktuk/domain/user/User.java
Labels: refactor, rename

#13 Dockerfile 작성 완료
  .gitignore
  Dockerfile
Labels: documentation

#17 refactor(all): @Comment 어노테이션 필수적이지 않은 부분 제거 #2
  src/main/java/com/example/tuktuk/domain/user/User.java
Labels: refactor

#19 Refactor(CourtTimeSlot): 도메인 2차 수정본
  src/main/java/com/example/tuktuk/domain/courttimeslot/CourtTimeSlot.java
  src/main/java/com/example/tuktuk/domain/courttimeslot/CourtTimeSlotId.java
  src/main/java/com/example/tuktuk/domain/courttimeslot/MatchFeeTable.java
  src/main/java/com/example/tuktuk/domain/courttimeslot/Participant.java
  src/main/java/com/example/tuktuk/domain/courttimeslot/ReservationStatus.java
  src/main/java/com/example/tuktuk/domain/courttimeslot/Time.java
  src/main/java/com/example/tuktuk/domain/courttimeslot/Type.java
  src/main/java/com/example/tuktuk/domain/global/DayType.java
  src/main/java/com/example/tuktuk/domain/global/Money.java
  src/main/java/com/example/tuktuk/domain/reservation/Reservation.java
  src/main/java/com/example/tuktuk/domain/slice/Slice.java
  src/main/java/com/example/tuktuk/domain/slice/SliceId.java
  src/main/java/com/example/tuktuk/domain/slice/SliceType.java
  src/main/java/com/example/tuktuk/domain/slice/borrow/Borrow.java
  src/main/java/com/example/tuktuk/domain/slice/borrow/BorrowStatus.java
  src/main/java/com/example/tuktuk/domain/slice/borrow/Borrower.java
  src/main/java/com/example/tuktuk/domain/slice/gamematch/Game.java
  src/main/java/com/example/tuktuk/domain/slice/gamematch/GameStatus.java
Labels: New Feature

#26 fix: localhost 환경에서 CORS 에러 해결 #2
  build.gradle
  src/main/java/com/example/tuktuk/config/CustomCorsConfig.java
  src/main/java/com/example/tuktuk/stadium/service/StadiumService.java
Labels: fix

#38 docs(dev-yaml): 개발 환경 log 레벨 설정 #37
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: documentation
